version: '3'
services:

  #PHP Service
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    container_name: volk-app
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./application:/var/www/html
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: volk-webserver
#    restart: unless-stopped
    tty: true
    ports:
      - "8888:8080"
    volumes:
      - ./application:/var/www/html
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

    #MySQL Service
  db:
    image: mariadb:10.2
#    image: mysql:5.7.22
    container_name: volk-db
    tty: true
    ports:
      - "3390:3306"
    environment:
      MYSQL_DATABASE: volk
      MYSQL_ROOT_PASSWORD: testeVolks
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local